### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by kwame101** [cretueusebiu/laravel-nuxt#10]
Hi great work once again. When I submit a form without entering anything (or invalid details) i get a 422 (Unprocessable Entity) from laravel and async promises error in the console but I managed to fix async error with try and catch. Could you help me fix the 422 error, it seems like its being sent from laravel when validation is wrong but I'm not sure where to catch it.

**Comment by kwame101** [comment]
In production build is there anyway to stop the validation errors from being logged into the console?

**Comment by cretueusebiu** [comment]
The `422 (Unprocessable Entity)` error message will always be shown. 
But if you don't want to show the exception from the promise you'll have to try/catch all the requests.

**Comment by kwame101** [comment]
Ahh ok thanks for your help, I can see the errors messages are triggered on response from laravel i.e 422 or 500 so its best to leave them
