### ISSUE TITLE
Cannot resolve "@nuxtjs/router" when running test 

### ISSUE THREAD

**Issue by jay7793** [cretueusebiu/laravel-nuxt#11]
Hi, I'm testing AVA with sample code from https://nuxtjs.org/examples/testing I have encountered an error: failed to resolve "@ nuxtjs / router"

I do not know what the problem is coming from. Please help me

![image](https://user-images.githubusercontent.com/11994458/36251114-8f261ce2-1272-11e8-8a3b-3cd0e208bf95.png)

**Comment by cretueusebiu** [comment]
Not sure what that could be. Maybe you have to instruct it to use that package somehow..
