### ISSUE TITLE
All routes return 404 when deploying on server

### ISSUE THREAD

**Issue by pcm0nk** [cretueusebiu/laravel-nuxt#117]
Im trying to upload both Laravel as a backend And Nuxt 2.11 as frontend (universal mode) into a server but after upload every routes returns 404, Im am also using nginx reverse proxy (production mode)

Upload Steps

1- upload backend files and folders ( app,bootstrap,client,config,database,routes,storage,vendor,package.json and lock,composer.json and lock)

2-upload frontend files and folders(.nuxt, and everything insdie my client folder)

3-In my server Ive added a new line at the end of my nginx.conf include /etc/nginx/sites-enabled/*.conf;

4- then in /etc/nginx/sites-enabled I have default.conf with the following content
```
server {
  # server on port 80 (default http port)
  listen 80;
  server_name rabter.com;

  # proxy for frontend
  location / {
    # nuxt server url
    proxy_pass http://localhost:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # proxy for api
  location /api/* {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    # laravel server url
    proxy_pass http://localhost:8000;
    proxy_redirect off;
  }
}
```

5- Ill setup pm2 server so I run pm2 start Laravel-nuxt to start listening to port 3000 ( lunching nuxt)

At this point I access my site which returns 404 on all routes no exception I also came across this https://github.com/iliyaZelenko/laravel-nuxt/issues/1#issuecomment-491484474 which I think it essentially what I want to do even tried the nginx code but didnt work

I have 0 routes in my web.php and all the routes are in api.php.Also this project works fine on localhost both dev and prod mode but when I move to the server its all 404.

**Comment by pcm0nk** [comment]
Also when Im running `nuxt run start` thsi message keeps repeating, like its in infinity loop
`Request failed with status code 502 12:30:02
  at createError (node_modules/axios/lib/core/createError.js:16:15)
  at settle (node_modules/axios/lib/core/settle.js:17:12)
  at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:236:11)
  at IncomingMessage.emit (events.js:322:22)
  at IncomingMessage.EventEmitter.emit (domain.js:482:12)
  at endReadableNT (_stream_readable.js:1187:12)
  at processTicksAndRejections (internal/process/task_queues.js:84:21) (repeated 0 times)
`

**Comment by Greenvold** [comment]
Hi,

I was facing this issue as well while deploying my website which uses this repo. I wasn't able to configure ngnix or apache in way that /api calls would work. Also laravel forge couldn't set it up. 

Solution for me was to setup completely new subdomain for api calls. api.domain.com. Then you setup whole apache/ngnix.conf file on your server. This works for me. Thing is that you have to modify few files in the project. RouteServiceProvider and api.php file if needed. There are many guides on the topic of how to user subdomain for api routing in laravel.
