### ISSUE TITLE
Implementing Laravel Echo Broadcasting

### ISSUE THREAD

**Issue by jericopulvera** [cretueusebiu/laravel-nuxt#12]
Hi, do you think it's easy to implement Laravel Echo Broadcasting with this app?

Thanks

**Comment by cretueusebiu** [comment]
Of course, I use it all the time. Just define it as a Vue plugin with ssr: false.

https://nuxtjs.org/guide/plugins#vue-plugins

**Comment by jericopulvera** [comment]
@cretueusebiu I can't make it work.

~plugins/laravel-echo.js
```
import LaravelEcho from "laravel-echo"

export default ({ app, store, redirect }) => {
    const token = store.getters['auth/token']

    window.Pusher = require('pusher-js');

    window.Echo = new LaravelEcho({
        authEndpoint: `${process.env.apiUrl}/broadcasting/auth`,
        broadcaster: 'pusher',
        key: '7db1d62cd6f616d60e89',
        cluster: 'ap1',
        auth: {
            headers: {
                Authorization: `Bearer ${token}`
            },
        },
    });
}
```

nuxt.config.js
```
 plugins: [
    '~components/global',
    '~plugins/i18n',
    '~plugins/vform',
    '~plugins/axios',
    '~plugins/fontawesome',
    { src: '~plugins/bootstrap', ssr: false },
    { src: '~plugins/laravel-echo', ssr: false }
  ],
```

I'm getting Status Code:500 Internal Server Error
on /broadcasting/auth

Please help me thanks!

**Comment by codeitlikemiley** [comment]
How to use it With SSR, ive decoupled the laravel and nuxt separately...
How do i access now the csrf_token in nuxt...

**Comment by codeitlikemiley** [comment]
@jericopulvera the fixed for you problem is just create a route for a login
instead of using LoginController set by laravel, you should create a redirect url for the login page of your front end app link....

**Comment by albay13** [comment]
Hey @jericopulvera, are you using api or web for your routes?
