### ISSUE TITLE
Basic usage incorrect ?

### ISSUE THREAD

**Issue by ganjarsetia** [cretueusebiu/laravel-nuxt#121]
I tried to follow the installation and the usage. I can access it at `http://localhost:3000` but when tried to login, it show error.
I believe this is because the API has not started yet. And I dont see to run the API/Backend in README.md

I think to solve this is to run: `php artisan serve`

**Comment by Greenvold** [comment]
Hi,

Yes if you are running xamp or laragon you definitely need to start the server as well. The api runs on this local environment.

**Comment by ganjarsetia** [comment]
@Greenvold Hi, I dont use that. Yes I know what you mean. But the Author is not give any instruction to run the API.
