### ISSUE TITLE
New mutation handler doesn't work

### ISSUE THREAD

**Issue by kwame101** [cretueusebiu/laravel-nuxt#13]
Hi, I created a mutation function in store/auth with action, getter and a state but when i called the getter function i get a null value. I debugged it and it seems like mutation is never called, any idea as to why or am I doing it wrong? 

this is my code 

```
import axios from 'axios'

export const state = () => ({
  name: null
})

export const getters = {
  name: state => state.name
}

export const mutations = {
  FETCH_DETAILS_SUCCESS (state, name) {
    state.name = name
  }
}

export const actions = {
  async getName ({ commit }) {
    try {
      const { data } = await axios.get('/username')

      commit('FETCH_DETAILS_SUCCESS', data)
    } catch (e) {
      // log error
    }
  }
}

```

And in my view component I did this 
```

 computed: mapGetters({
    name: 'auth/name'
  }),

  created () {
   //it returns null 
    console.log(this.name)
  },
```

Although when i change your fetchUser async call to get username instead of user it works but my new function doesn't work and all return null

**Comment by cretueusebiu** [comment]
Sorry, but this is more a Vuex question. Try using the Vue Chrome extension to debug the store.

**Comment by kwame101** [comment]
Could be it be a bug or me having typo somewhere in my code? because when I change one of your async functions it works but with my one i get null 😕

**Comment by cretueusebiu** [comment]
Remove the try/catch or a add a log to see maybe it's something from the request to the server.
