### ISSUE TITLE
"Make sure to run npm run build!" from SpaController.php

### ISSUE THREAD

**Issue by GitCodeDestroyer** [cretueusebiu/laravel-nuxt#134]
`localhost:3000` is working very good (login, registration...).
I have ran `npm run build.`

Why this error appearing or for what?
Maybe, you should abort 404 error?

**Comment by eli007s** [comment]
hey @GitCodeDestroyer 

this happens because `npm run build` needs to call `nuxt build` so it can create the `_nuxt` directory.

**Comment by GitCodeDestroyer** [comment]
Oh! Thanks @eli007s... Indeed, _nuxt folder is needed
