### ISSUE TITLE
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by maprangsoft** [cretueusebiu/laravel-nuxt#141]
i sent data to axios backend use  dd($request->all()); when view in network tap in browser i can't see response from backend
in console error blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

backend
<img width="897" alt="Screen Shot 2564-01-17 at 15 06 51" src="https://user-images.githubusercontent.com/25447955/104834972-e947b080-58d5-11eb-9da9-ff9cd9c05d74.png">

send request
<img width="1627" alt="Screen Shot 2564-01-17 at 15 07 19" src="https://user-images.githubusercontent.com/25447955/104834992-054b5200-58d6-11eb-9d28-2bb3ce87cdb4.png">

in network tap
<img width="883" alt="Screen Shot 2564-01-17 at 15 08 07" src="https://user-images.githubusercontent.com/25447955/104835002-1eec9980-58d6-11eb-9327-7facc15c84bd.png">

<img width="883" alt="Screen Shot 2564-01-17 at 15 08 16" src="https://user-images.githubusercontent.com/25447955/104835008-27dd6b00-58d6-11eb-9016-4d59af85a81d.png">

please how to fix this problem i want see response from dd() in network tap preview.

**Comment by cretueusebiu** [comment]
Try this 
https://github.com/fruitcake/laravel-cors/issues/301#issuecomment-379894963

**Comment by maprangsoft** [comment]
thank you very much problem has resolved.

<img width="820" alt="Screen Shot 2564-01-18 at 21 24 48" src="https://user-images.githubusercontent.com/25447955/104927265-c8fe1b80-59d3-11eb-9a44-6a9d2cb5bc5d.png">
