### ISSUE TITLE
How to Use laravel Echo with a Decoupled Laravel and Nuxt 

### ISSUE THREAD

**Issue by codeitlikemiley** [cretueusebiu/laravel-nuxt#15]
On the Documentation of Laravel Echo, we need the csrf token
Any Help with this?
First Question if disbling csrf token , the best choice?
Or We need to make an endpoint to fetch on the initial page load
The Csrf token and simply add it to your store...
I wanna here your reaction to this approach... and ho w you would do it on your SSR version that is decoupled laravel and nuxt

**Comment by cretueusebiu** [comment]
I don't think you need a csrf token since you're using jwt for authentication.
