### ISSUE TITLE
Can't access laravel on localhost 

### ISSUE THREAD

**Issue by donchoborisov** [cretueusebiu/laravel-nuxt#150]
Hi there, 

I am successfully installing the package I can run the nuxt app on port 3000 but when I type php artisan serve an try to access the backend error MAKE SURE TO RUN NPM BUILD.

Can you please help me with issue ?

Thank you very much in advance

**Comment by cretueusebiu** [comment]
You have to run `npm run build`

**Comment by donchoborisov** [comment]
I am having error again when I run npm run build

**Comment by donchoborisov** [comment]
its working now thanks

**Comment by donchoborisov** [comment]
Now after installation if i try to install any dependencies its showing me that

Auth driver [jwt] for guard [api] is not defined
