### ISSUE TITLE
Login with name instead of email

### ISSUE THREAD

**Issue by sdevogel** [cretueusebiu/laravel-nuxt#151]
Hi, thanks for the boilerplate. 
I was wondering and have been searching around the project, but is it possible to login with the users name instead of the email?

Where would you change the authentication?

thank!

**Comment by cretueusebiu** [comment]
You'll have to add a `username` method in [LoginController.php](https://github.com/cretueusebiu/laravel-nuxt/blob/master/app/Http/Controllers/Auth/LoginController.php):

```php
public function username()
{
   return 'username';
}
```

and then replace `email` with `username` in [login.vue](https://github.com/cretueusebiu/laravel-nuxt/blob/master/client/pages/auth/login.vue)
