### ISSUE TITLE
Classic laravel page on subdomain

### ISSUE THREAD

**Issue by rudolfbruder** [cretueusebiu/laravel-nuxt#153]
Hi,

I absolutely love this template package. I am facing one issue after long term usage. I am in need of deploying classic laravel app which uses laravel breezee as auth on a subdomain.

However when i scaffold the basic breezee auth and try to build there is a conflict between webpack versions because nuxt is using 4.46.0 but the latest laravem mix uses v5. 

Can you think of any way how i could build classic laravel css,js via mix and as well successfully run nuxt build?

I am really lost about this right now and I would very much appreciate your help.

Here is the error message when running npm run development (mix) :
```
$ npm run development

> development
> mix

[webpack-cli] Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.chunkFilename should be a string.
   -> The filename of non-entry chunks as relative path inside the `output.path` directory.
 - configuration.stats has an unknown property 'preset'. These properties are valid:
   object { all?, assets?, assetsSort?, builtAt?, cached?, cachedAssets?, children?, chunkGroups?, chunkModules?, chunkOrigins?, chunks?, chunksSort?, colors?, context?, depth?, entrypoints?, env?, errorDetails?, 
errors?, exclude?, excludeAssets?, excludeModules?, hash?, logging?, loggingDebug?, loggingTrace?, maxModules?, moduleAssets?, moduleTrace?, modules?, modulesSort?, nestedModules?, optimizationBailout?, outputPath?, performance?, providedExports?, publicPath?, reasons?, source?, timings?, usedExports?, version?, warnings?, warningsFilter? }`
```

Thank you!

**Comment by cretueusebiu** [comment]
First try upgrading Nuxt to the latest version and see if it has support for Webpack 5 (it doesn't mention it here though https://nuxtjs.org/docs/release-notes)

Otherwise you could split the client into another repo:
https://github.com/cretueusebiu/laravel-nuxt#notes

**Comment by rudolfbruder** [comment]
Indeed i have latest nuxt but its still depending on v4 webpack. So I incline to the repo split.

I got laravel breezee installed and built, the only problem is that it doesnt log me in. Instead i face this error message

` Header may not contain more than a single header, new line detected `

No idea what's that about to be honest.

**Comment by rudolfbruder** [comment]
It's connected to Authenticate.php file and this has to be added there, route instead of redirect.

```
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            return route('admin.login');
        }
    }
```

Anyways breezee still cant authenticate users via email and password.

**Comment by rudolfbruder** [comment]
Fixed by using proper Auth::guard('web')->user().... in places where web guard is needed.
