### ISSUE TITLE
Forms not working

### ISSUE THREAD

**Issue by tankerkiller125** [cretueusebiu/laravel-nuxt#16]
I have a completely blank, not modified version of this project, latest release, and I can not get any of the forms to work. Looking at the network request it shows that it is sending a request to the server as a OPTIONS request.

The problem though is that when I use postman to make the request to the server I get a 500 error about missing a _nuxt/index.html file. But when I add the Accept: application/json header to the request it works perfectly. But I can not find how to add this header to all the form request.

**Comment by tankerkiller125** [comment]
I've done some further research and found that the OPTIOSN request before sending the post request is normal. But I'm still having this issue, I have the server running in homestead and the actual application running on my actual machine, The CORS config is set to allow any host and all the headers that the post request plans to use. When I make the options request in postman everything comes back perfectly with Preflight: OK but the actual frontend gets nothing, not even a 403

**Comment by cretueusebiu** [comment]
I use [laravel-cors](https://github.com/spatie/laravel-cors) for CORS so take a look at the config of that package.

**Comment by tankerkiller125** [comment]
I've set it up so that everything is allowed, and still nothing. I even tried switching to the other major cors package with allowing everything with no success

**Comment by tankerkiller125** [comment]
I think I've narrowed the issue to the Host header being sent because that causes a no file specified error.

**Comment by tankerkiller125** [comment]
Ok, further information, if I run the php artisan serv HTTP server everything works from the postman side of things (exact same headers as the form module is sending) but the ajax is still not working.

**Comment by tankerkiller125** [comment]
I'm going to close this issue as I got the php artisan serv command to work finally. But I still can't get it working inside homestead. I'm thinking its some sort of homestead nginx config that I'll figure out eventually.

**Comment by michalbursik** [comment]
@tankerkiller125 

I have the same problem. What was your solution ?
