### ISSUE TITLE
how to deploy on server ?

### ISSUE THREAD

**Issue by tmediaa** [cretueusebiu/laravel-nuxt#17]
node version: v9.11.1
php ver: PHP 7.1.16 
npm ver: 5.6.0

when i deploy on hosting i got a error like this : 
`"file_get_contents(/home/tmediair/public_html/public/_nuxt/index.html): failed to open stream: No such file or directory"`

my question is a there any complete guide to deploy laravel-nuxt on hosting ?

**Comment by cretueusebiu** [comment]
Make sure the environment is set to production and run npm run build
