### ISSUE TITLE
_nuxt folder is missing

### ISSUE THREAD

**Issue by Iworb** [cretueusebiu/laravel-nuxt#18]
Nuxt compiles his file into `.nuxt` directory in the root and builds it to `.nuxt/dist`, so `_nuxt` folder inside `public` doesn't created, that's why this error appeared:
```
ErrorException (E_WARNING)
file_get_contents(D:\OSPanel\domains\ln.ll\public\_nuxt/index.html): failed to open stream: No such file or directory:
Route::get('{path}', function () {
    return file_get_contents(public_path('_nuxt/index.html')); // <----
})->where('path', '(.*)');
```
Did you try to make clean installation step by step following `readme`? Or maybe there's some missing content for settings?

**Comment by cretueusebiu** [comment]
If you don't use SSR make sure to follow the guide https://github.com/cretueusebiu/laravel-nuxt#production-without-ssr and set the app env to production.

**Comment by Iworb** [comment]
I'm in SSR mode.
1. Set `GITHUB_CLIENT_ID`
2. run `yarn run build`
3. run `yarn run start`
4. visit `http://localhost:3000/login`
5. press 'Login with github' and got this error.

**Comment by cretueusebiu** [comment]
You have 2 options to run this: 

- with SSR (default) where you would access it via http://localhost:3000 
- without SSR where you have to follow the guide, set the app env to `production`, run `npm run build` then visit `http://yourapp.test` without running `npm run start` (like a normal Laravel app).
