### ISSUE TITLE
Update to Laravel 5.6?

### ISSUE THREAD

**Issue by tankerkiller125** [cretueusebiu/laravel-nuxt#19]
Is their any planned update to migrate to Laravel 5.6?

**Comment by cretueusebiu** [comment]
You only have to upgrade the dependencies: https://laravel.com/docs/5.6/upgrade#upgrade-5.6.0

**Comment by alainperrier** [comment]
I tried to update to Laravel 5.6, it seems to work ok, but when I refresh the page, vuex reset the store and the app doesn't recognize me as authenticated, although I am (the cookie is still set, and I need to manually logout from Postman before being able to login again) @cretueusebiu

**Comment by tankerkiller125** [comment]
I found you have to update all of the dependencies as well as update the trustedproxy Middleware and several other minor issues.
