### ISSUE TITLE
_nuxt/index.html is not found in directory

### ISSUE THREAD

**Issue by codeitlikemiley** [cretueusebiu/laravel-nuxt#2]
im getting this error

```
file_get_contents(C:\Users\uriah\sites\www\laravel-nuxt\public\_nuxt/index.html): failed to open stream: No such file or directory
```
there suppose to be a folder of _nuxt and index.html but there is none, 
may i know if that is generated dynamically or its static

**Comment by cretueusebiu** [comment]
It's only generated when you run `npm run build` and you enabled spa mode.

**Comment by codeitlikemiley** [comment]
i tried doing it but _nuxt folder with index.html is not generated

**Comment by cretueusebiu** [comment]
Fixed in the latest release.

**Comment by riazXrazor** [comment]
@cretueusebiu  still its not generating

**Comment by tallcoder** [comment]
Running into the same issue. I'm sure I'm missing something, but was hoping this thread would say what that was.

**Comment by veed76** [comment]
Hi @cretueusebiu I also face same issue.

**Comment by Greenvold** [comment]
Hi still facing the issue. Is there some workaround how to use this project in dev mode and make api calls etc?

**Comment by milosb793** [comment]
I had the same issue, and I think I've solved it via `nuxt generate`

**Comment by fatm-dev** [comment]
instead of using file_get_contents(_nuxt/index.html)
use   file_get_contents(_nuxt\index.html).
