### ISSUE TITLE
nuxt generate

### ISSUE THREAD

**Issue by AlexeyTcapaev** [cretueusebiu/laravel-nuxt#20]
Hi,in docs i'm not found settings for nuxtjs mode - generate ,it is possible in this project?

**Comment by cretueusebiu** [comment]
I think it should work.

**Comment by AlexeyTcapaev** [comment]
I tried but it did not work out yet

**Comment by OleksiiBrylin** [comment]
> I tried but it did not work out yet

Did you find solution?
