### ISSUE TITLE
Not an issue, more of a question. Is it feasible for Laravel Spark to integrate with laravel-nuxt?

### ISSUE THREAD

**Issue by admench** [cretueusebiu/laravel-nuxt#21]
Not an issue, more of a question. 
Is it feasible for Laravel Spark to integrate with laravel-nuxt?

Thanks for what seems to be a fantastic package.

**Comment by admench** [comment]
Presumably it would be better to start a fresh Laravel Spark app, and provide an API to a separate Nuxt project in this case.

https://spark.laravel.com/docs/6.0/api

**Comment by cretueusebiu** [comment]
This is just an template example that can be modified to work with Spark. But you'll have to re-write a lot to port it from blade views to vue templates.

I was thinking about a "pro" version of a spa project with more features, like billing, admin, etc.

**Comment by admench** [comment]
In my situation, I feel it may be best to split the app up with app-centric pages handled by nuxt, and let laravel spark handle the account pages itself. This would have to be handled by a clever nginx config to handle requests and pass them to either nuxt or laravel's routing.
