### ISSUE TITLE
Can't access OWN api endpoints

### ISSUE THREAD

**Issue by jariesdev** [cretueusebiu/laravel-nuxt#22]
I was testing and trying your start template but unable to connect or access the api endpoints even accessing it via browser like http://localhost:3000/test which I put 

Route::get('/test', function(){
    return ['a' => 'data a','b' => 'data b'];
});

the login returns "Unhandled promise rejection " because of 404.

**Comment by cretueusebiu** [comment]
You can't access the backed routes anymore. Unless you use a proxy or something.

**Comment by jariesdev** [comment]
Can you tell me why Or how? Im confuse the use of laravel

**Comment by WesThorburn** [comment]
I highly recommend documenting this somewhere, this is a very common point of confusion for devs.
