### ISSUE TITLE
Question about SSR and the nodejs server

### ISSUE THREAD

**Issue by chucko86** [cretueusebiu/laravel-nuxt#24]
Hi ! 

Thank you for this amazing package! :D 

I am fairly new to vuejs, Nuxtjs SSR with Laravel and I have a hard time understand how it works. Since I am using Laravel on my server to do all the backend stuff, do I need to have another server with  nodejs running and if yes, is the only purpose of that nodejs server, to serve server side rendered files ? It wont deal with autorisation and authentication at all? 

Thank you for your time.

**Comment by cretueusebiu** [comment]
If you don't need it then don't even bother and just use it as a classic SPA. 

But with SSR, you get all the benefits of a single page application, but you also have the page rendered on the server for better SEO.

Check the Vue and Nuxt docs for more about SSR.

You don't need 2 servers for SSR, just a Node process that generates the initial page. Everything else works the same.

**Comment by chucko86** [comment]
Exactly, I am doing it to have a better SEO. If it wouldn't be of SEO, Laravel and vuejs would be just fine in SPA mode. Since I want to achieve this for SEO purposes. What would be the preferred setup? Two servers? One running Laravel and another one with nodejs to handle the rendering so that the SEO is taken into consideration?

Thank you for your quick response, it was really  appreciated!

**Comment by cretueusebiu** [comment]
You don't need 2 servers. You have your Laravel application and then you just open a Node process on the same server for Nuxt.

**Comment by chucko86** [comment]
Thanks a lot!
