### ISSUE TITLE
problem with children routes

### ISSUE THREAD

**Issue by tmediaa** [cretueusebiu/laravel-nuxt#25]
my parent/child route like this in router,js:

```
{
        path: '/admin/base',
        component: Navs,
        children: [
            {path: 'breadcrumbs', component: Breadcrumbs},
            {path: 'cards', component: Cards}
        ]
    },
```
when i navigate to admin/base/breadcrumbs my app got a error like this:

`Converting circular structure to JSON`

i want to understand why this problem occured

**Comment by cretueusebiu** [comment]
Please post a reproduction link.

**Comment by tmediaa** [comment]
@cretueusebiu  Did you check it out?

**Comment by Frozire** [comment]
@tmediaa could you push the changes? The code you provided isn't in the given repository.
