### ISSUE TITLE
Working with Laravel Dusk?

### ISSUE THREAD

**Issue by InstanceOfMichael** [cretueusebiu/laravel-nuxt#26]
When you run Laravel Dusk, Dusk will swap the .env file. This doesn't work with the way `laravel-nuxt` works with php artisan serve. Also, using nuxt in production mode won't work because Vue warnings and some other debug stuff don't work without nuxt dev server (I checked).

**Comment by cretueusebiu** [comment]
This doesn't work with Dusk. Try using [Vue Test Utils](https://github.com/vuejs/vue-test-utils).
