### ISSUE TITLE
Problem with upath module

### ISSUE THREAD

**Issue by bovisp** [cretueusebiu/laravel-nuxt#27]
I'm running WAMP on Win 10 using `yarn 1.9.4` and `node  10.8.0`.

I ran `composer create-project --prefer-dist cretueusebiu/laravel-nuxt` as per your readme and that was all fine.

I was able to migrate the database tables as well.

When I came to `yarn`, I got this error:

```
error upath@1.0.2: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I guess I'm using the wrong version of Node, but is there a way around this if I want to use Node > 9.x.x?

**Comment by cretueusebiu** [comment]
Try `yarn install --ignore-engines` or delete `yarn.lock` and then `yarn install --ignore-engines`

**Comment by bovisp** [comment]
OK. This worked. Thanks for your help. Closing issue.
