### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by FilipJedrasik** [cretueusebiu/laravel-nuxt#28]
Hi. I've followed instructions to change **mode to spa**, done some migrations and just tested register. It isn't working. I'm getting 500 error in console. I've found there are bad(?) routes to register and login. **Changed it to:**
`Route::post('login', 'Auth\LoginController@attemptLogin');
    Route::post('register', 'Auth\RegisterController@register');`

**attemptLogin yet exists. Register looks like that:**
`public function register(Request $request){
        if(!Validator::make($request, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
        ]))
            return response([
                'status' => 'error',
                'msg' => 'Validation failed'
            ], 400);

        $user = new User;
        $user->email = $request->email;
        $user->name = $request->name;
        $user->password = bcrypt($request->password);
        $user->save();

        return response([
            'status' => 'success',
            'data' => $user
        ], 200);
    }`

Another log(which means nothing to me):

> Error: Request failed with status code 500
    at FtD3.t.exports (vendor.7f943d49379b19889618.js:2)
    at t.exports (vendor.7f943d49379b19889618.js:2)
    at XMLHttpRequest.d.(anonymous function) (http://localhost:8000/_nuxt/vendor.7f943d49379b19889618.js:2:90914)

How to make register and login work?

**Comment by cretueusebiu** [comment]
Check the network tab or laravel.log for the full error
