### ISSUE TITLE
Problems with the i18n plugin and Nuxt 2.0.0

### ISSUE THREAD

**Issue by samuelterra22** [cretueusebiu/laravel-nuxt#30]
I am having problems with translating some keys after I upgraded to version 2.0.0 of Nuxt. As much as I define the translation of the text in json, the translation of the site is partially done, ie it is as if the plugin read only half of the json. Any idea what might be happening?

Did you even try to update the project?

Follows an image with the error given in the console

![image](https://user-images.githubusercontent.com/11915449/46219588-1c895e80-c31e-11e8-99b5-49e5242a2b22.png)

**Comment by cretueusebiu** [comment]
I'm waiting a bit before upgrading to Nuxt 2.

**Comment by koekaverna** [comment]
I updated to nuxt 2.1.0 and everything works correctly for me.
Try to replace " " to "_" and remove dots from translation keys.

**Comment by samuelterra22** [comment]
It's working properly. It was probably some coding error. I'm using `vue-i18n` in version `8.3.2` and `Nuxtjs` in version `2.3.4`. Thank you for your help!
