### ISSUE TITLE
Mail from laravel has link to the api

### ISSUE THREAD

**Issue by koekaverna** [cretueusebiu/laravel-nuxt#31]
In header of the letters (recover password, etc) in header of the letter 
```
<td class="header" style="font-family: Avenir, Helvetica, sans-serif; box-sizing: border-box; padding: 25px 0; text-align: center;">
        <a href="http://api.my-site.local" style="font-family: Avenir, Helvetica, sans-serif; box-sizing: border-box; color: #bbbfc3; font-size: 19px; font-weight: bold; text-decoration: none; text-shadow: 0 1px 0 white;">
            My App Name
        </a>
    </td>
</tr>
```
In `.env`: 
```
APP_URL=http://api.my-site.local
CLIENT_URL=http://my-site.local
```
The link could be to the `env.CLIENT_URL` not to `env.APP_URL`

**Comment by M-Abdullahi** [comment]
I was facing the same issue in password reset emails.
I think the best approach is to create your own mailable class and customize the view.

**Comment by cretueusebiu** [comment]
You can run `php artisan vendor:publish --tag=laravel-mail` and customize the views to include the actual client url.
