### ISSUE TITLE
Vuex-CRUD didn't work: Method [viaRemember] does not exist

### ISSUE THREAD

**Issue by votintsev** [cretueusebiu/laravel-nuxt#32]
Hi.

I tried use library https://github.com/JiriChara/vuex-crud with your package. But when I call to api I get 500 error: 

> message: "Method [viaRemember] does not exist.", exception: "BadMethodCallException",…}
exception: "BadMethodCallException"
file: "/var/www/varus/vendor/tymon/jwt-auth/src/JWTGuard.php"
line: 445
message: "Method [viaRemember] does not exist."

So, as I understand I should use axios from nuxt plugin. But if I try something like:

```
import createCRUDModule from 'vuex-crud';
import axios from 'axios'

const crudModule = createCRUDModule({
    resource: 'domain',
    urlRoot: '/domain',
    client: axios
});

const state = () => crudModule.state;

const { actions, mutations, getters } = crudModule;

export {
    state,
    actions,
    mutations,
    getters
};

```
It is not working. How can I adjust it? Or how can I put right interceptors.request?

Update. I try: ```client: window.$nuxt.$axios``` ( as described: https://github.com/nuxt-community/axios-module/issues/28 and https://github.com/JiriChara/vuex-crud/issues/19 ) but it is not work too.

**Comment by cretueusebiu** [comment]
Looking at that package, you have to instantiate the store manually https://nuxtjs.org/guide/vuex-store

**Comment by votintsev** [comment]
@cretueusebiu Thank you for your answer.

Unfortunately, I can't find how to do this from the documentation. If you'd be so kind as to set a little example, you'd be a great help me!
