### ISSUE TITLE
Any have an Apache configuration example ?

### ISSUE THREAD

**Issue by ysfkaya** [cretueusebiu/laravel-nuxt#38]
First of all, thanks for this boilerplate. I'm finished the my own project. And finally I deploy it to an apache server. Run command `npm run start` and then it listening "domain.name:3000". But I want to the not show the port number. 

I tried everything but failed. Is there an apache configuration example for this?

**Comment by amjadkhan896** [comment]
@ysfkaya I have the same problem. did you solve the problem?
I made two virtual hosts. and make the client separate from the laravel.

**Comment by ysfkaya** [comment]
No I didn't solve, I changed server to nginx
