### ISSUE TITLE
Update next.js

### ISSUE THREAD

**Issue by itranga** [cretueusebiu/laravel-nuxt#39]
When do you plan to update next.js to 2.3.4 ?

**Comment by itranga** [comment]
When do you plan to update ?

**Comment by cvaize** [comment]
I updated all the dependencies and everything works for me. Be sure to add the last 3 dependencies for proper operation.
![image](https://user-images.githubusercontent.com/26907947/60768438-5ec9a280-a0dd-11e9-9c96-f88c896480a8.png)

**Comment by cretueusebiu** [comment]
You can try the next branch.

**Comment by cretueusebiu** [comment]
[2.0](https://github.com/cretueusebiu/laravel-nuxt/releases/tag/2.0.0) has been released!
