### ISSUE TITLE
Why does the token expire when the page refreshes?

### ISSUE THREAD

**Issue by jay7793** [cretueusebiu/laravel-nuxt#4]
Token will expire immediately when I try to refresh the page. I do not know if it's due to my application malfunction or whether it's normal for the token.

Thank you.

**Comment by cretueusebiu** [comment]
The ttl of the token is 60 minutes [by default](https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php#L103).

If it expires immediately there's something wrong with the app. Are you using the current template or you have a custom build ?

**Comment by jay7793** [comment]
I think the problem is probably due to my development environment. I'm not sure what the problem is coming from Laravel because there is no error on the client side.

**Comment by jay7793** [comment]
Hi,
I solved the problem by re-generate jwt token using `php artisan jwt:secret` command

**Comment by cretueusebiu** [comment]
When you install the project via composer it will run that command for you. But if you just clone it you'll have to run it manually (as you do with `php artisan key:generate`).
