### ISSUE TITLE
How do I retrieve data from laravel backend using axios call?

### ISSUE THREAD

**Issue by BennieBe** [cretueusebiu/laravel-nuxt#40]
Hi there, I have a simple question about this project. I am trying to use it as a template to migrate my vue-laravel project to a nuxt-laravel project. Now I need to get some data from laravel backend to display it in my component but I am struggling to understand where to define the route to reach my laravel backend.

I tried it like this here:
Frontend axios call:
```
async asyncData ({ $axios }) {
  if (process.server) {
    return $axios.$get('/api/data')
    .then((res) => {
      this.data = res.data;
    })
  }
}
```

Backend call in api.php:
`Route::get('/data', 'HomeController@index');`

But I am constantly getting a 404 in any way I try to define the route ...
Do I need to add something into vue-router? 
If yes how do I define a route that does not call a specific component but only pulls data from backend?
If no what do I need to do otherwise?

I would be grateful for some example that I can work with to get this to work :)

Thanks in advance!

**Comment by d4rkr3pt0r** [comment]
@BennieBe Did you try complete url instead of `'/api/data'` ?

**Comment by d4rkr3pt0r** [comment]
@BennieBe Did you try complete url instead of `'/api/data'` ?

**Comment by Geowan** [comment]
You may need to configure axios base url

Example in my project i have setup axios like

I have also added the dotenv axios module so that i can simply load env url for axios


So simply in your nuxtjs config add 
        
          modules: [
             '@nuxtjs/axios', '@nuxtjs/dotenv'
           ],
          axios: {
             baseURL: Env.get('AXIOS_BASE_URL', 'https://myurl.com'),
          },

So in your usual env file add

          AXIOS_BASE_URL=http://myapiurl


So when you call 
 
           $axios.$get('/api/data')

It will translate to http://myapiurl/api/data

**Comment by BennieBe** [comment]
Hi @Geowan alright, I will try this, thanks!
