### ISSUE TITLE
 session management returns null

### ISSUE THREAD

**Issue by davizxtr** [cretueusebiu/laravel-nuxt#42]
Is it possible to use sessions with laravel in this project? The session is not persistent, for each request a new one is generated without taking into account the previous one. Does not generate cookie laravel_session. 

I save with: session(['languages' => $all_languages])
and read with $all_languages ​​= session('languages') but it always returns null.

What is the best way to work with sessions?

**Comment by cretueusebiu** [comment]
No, it doesn't work since this is stateless.
