### ISSUE TITLE
UPDATE NUXT

### ISSUE THREAD

**Issue by davizxtr** [cretueusebiu/laravel-nuxt#43]
Hi!
I try to update nuxt and it is giving me problems.
`npm install nuxt@^2.6.3`

It is possible to upgrade to version 2.6.3 ?
I have to do some extra configuration?

Thanks

**Comment by cretueusebiu** [comment]
[2.0](https://github.com/cretueusebiu/laravel-nuxt/releases/tag/2.0.0) has been released!
