### ISSUE TITLE
Is laravel version tightly coupled?

### ISSUE THREAD

**Issue by M-Abdullahi** [cretueusebiu/laravel-nuxt#47]
First of all, thank you for creating this project. 
I played around with it and wanted to know if laravel version is tighly coupled to the nuxt version. can it be upgraded to 5.8 without breaking anything?

**Comment by cretueusebiu** [comment]
You can upgrade to 5.8 without any problems.

I plan to update this template sometime this week. You can check the next branch for progress.

**Comment by M-Abdullahi** [comment]
Thank you.
