### ISSUE TITLE
Auth logged out when page refreshed

### ISSUE THREAD

**Issue by jay7793** [cretueusebiu/laravel-nuxt#5]
I think the problem is similar to this [issue](https://github.com/nuxt/nuxt.js/issues/972#issuecomment-332830464). I have educated it. but I don't know how to implement with my project. Can you help me?

**Comment by cretueusebiu** [comment]
Make sure you have a jwt token in your .env file https://github.com/cretueusebiu/laravel-nuxt/issues/4

Post your project so I can take a look.

**Comment by jay7793** [comment]
Thank you. I invited you on bitbucket

**Comment by cretueusebiu** [comment]
This commit https://github.com/cretueusebiu/laravel-nuxt/commit/18653c72f26bbb9f2215a76907a46321e5420490 fixes the axios headers.

**Comment by cretueusebiu** [comment]
This is a template project, you usually clone it and work on your project. It's not quite possible to update it as a package. You'll just have to go through the commits and apply those changes to your project. 
I pushed a commit with that fix to your repo.

**Comment by jay7793** [comment]
Thanks a lot for suggest
