### ISSUE TITLE
Is this project maintained anymore?

### ISSUE THREAD

**Issue by tankerkiller125** [cretueusebiu/laravel-nuxt#56]
It seems like this project is no longer maintained, it's been a year since any commits where pushed and in that time Nuxt has been updated drastically. And laravel has also been updated. It also seems that question and issues are going completely unanswered.

If it is unmaintained I don't want to blame anyone for it, I get that everyone gets busy but it would be nice to know upfront if that is the case so that people can make decisions if they want to spend the time update the package themselves, deal with out of date versions, or even try to find another solution.

**Comment by cretueusebiu** [comment]
There is a `next` branch with Nuxt 2.7.
I just have to upgrade to the latest version of Laravel and release it.

**Comment by tankerkiller125** [comment]
Awesome! I was looking to see if there was a newer branch but didn't see one, maybe I missed it? Either way it's good to know that it's still being updated and maintained.

**Comment by cvaize** [comment]
https://github.com/cretueusebiu/laravel-nuxt/issues/39#issuecomment-508996268

**Comment by cretueusebiu** [comment]
[2.0](https://github.com/cretueusebiu/laravel-nuxt/releases/tag/2.0.0) has been released!
