### ISSUE TITLE
Login with github is not working

### ISSUE THREAD

**Issue by jericopulvera** [cretueusebiu/laravel-nuxt#6]
Uncaught (in promise) TypeError: Cannot read property 'focus' of null

I added these two at my .env

GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=

**Comment by cretueusebiu** [comment]
Sometime the browser will block popups and you have to manually allow it:

![screenshot](https://user-images.githubusercontent.com/1517945/35243054-3f789cbc-ffc4-11e7-9974-5637d7f4dd1a.png)

**Comment by jericopulvera** [comment]
GREAT!!!
