### ISSUE TITLE
Upgrade to Laravel 5.8.x

### ISSUE THREAD

**Issue by connecteev** [cretueusebiu/laravel-nuxt#61]
@cretueusebiu thanks for this repo...it's much needed!
Can we upgrade to Laravel 5.8.x?

**Comment by cretueusebiu** [comment]
I hope I can release a new version this week with everything up to date.

**Comment by connecteev** [comment]
Great thanks @cretueusebiu. I hope to keep using this repo, appreciate you keeping it up to date.

By the way, this is off-topic, but would it be possible to have a laravel + nuxt example with social login/authentication using socialite (for one of google, facebook, linkedin, twitter as an example)?

**Comment by cretueusebiu** [comment]
[2.0](https://github.com/cretueusebiu/laravel-nuxt/releases/tag/2.0.0) has been released!

**Comment by connecteev** [comment]
Awesome, thanks! Look forward to trying it out
