### ISSUE TITLE
Suggestion: Don't use @nuxtjs/router and override the default Nuxt routing functionality

### ISSUE THREAD

**Issue by connecteev** [cretueusebiu/laravel-nuxt#62]
@cretueusebiu thanks for sharing this repo, we thank you for it.

THis is just a suggestion, and I've seen the comment here:
https://github.com/cretueusebiu/laravel-nuxt/issues/33
What is the advantage of using this module: https://github.com/nuxt-community/router-module with a router.js file instead of auto-route generation from the pages/ directory?

Instead of overriding the default nuxt routing config functionality, why not add aliases or register custom routes instead of using @nuxtjs/router
This will allow this repo to be more compliant with other nuxt code, allowing us to copy paste from other repos into our application.

**Comment by cretueusebiu** [comment]
I always prefer to have my routes defined in a file, but I guess since this template is intended more as starting point I could remove it and leave it with the default router.

I will try to release a new version soon and will consider this change.

**Comment by connecteev** [comment]
@cretueusebiu I am *very* new to nuxt (or vue for that matter) so I defer to the experts (aka you) as I don't know how much "extra power" the router.js file provides. I do believe that consistency with the other nuxt codebases would be helpful to me (and others will adopt it more easily), so thanks for the consideration.

**Comment by cretueusebiu** [comment]
It didn't make it into [2.0](https://github.com/cretueusebiu/laravel-nuxt/releases/tag/2.0.0). It requires aliasing a bunch of routes...
