### ISSUE TITLE
Unable to register after new installation

### ISSUE THREAD

**Issue by connecteev** [cretueusebiu/laravel-nuxt#66]
@cretueusebiu 

I went through the usual steps in the README and I am trying to get this repo to work on my dev machine in SSR mode. I have npm run dev running on localhost:3000 and php artisan serve running on localhost:8000 

However, I keep seeing a "Network Error: An error occurred while rendering the page. Check developer tools console for details." when I enter data at and try to register from http://localhost:3000/register 
The console.logs show:
```

Unchecked runtime.lastError: The message port closed before a response was received.
register:1 Access to XMLHttpRequest at 'http://localhost/api/register' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
vendors.app.js:17293 error Error: Network Error
    at createError (commons.app.js:762)
    at XMLHttpRequest.handleError (commons.app.js:297)
value @ vendors.app.js:17293
value @ vendors.app.js:17293
value @ vendors.app.js:17293
(anonymous) @ vendors.app.js:17293
push../.nuxt/client.js.vue__WEBPACK_IMPORTED_MODULE_18__.default.config.errorHandler @ app.js:311
globalHandleError @ commons.app.js:13274
handleError @ commons.app.js:13243
(anonymous) @ commons.app.js:13260
Promise.catch (async)
invokeWithErrorHandling @ commons.app.js:13260
invoker @ commons.app.js:13583
original._wrapper @ commons.app.js:18306

```

Btw I went through the usual steps in the README, and made the following changes:
.env file:
```
APP_URL=http://localhost:8000
CLIENT_URL=http://localhost:3000
```

nuxt.config.js (commented out mode: 'spa'
```
module.exports = {
//  mode: 'spa', // Comment this for SSR

```
Not sure if there's something missing in the install instructions but I haven't been able to get it to work today. I'm not sure but I think it was working before? Is something missing from what you can see here?

**Comment by cretueusebiu** [comment]
It says "Access to XMLHttpRequest at 'http://localhost/api/register' from origin".
It looks like the `APP_URL` is set to `http://localhost` instead of `http://localhost:8000`.
Make sure to stop/start both `php artisan serve` and `npm run dev` as the .env is not reloaded when changes are being made.

**Comment by connecteev** [comment]
@cretueusebiu Interesting, that worked. It must have been the server restart that did it, because I remember trying APP_URL=http://localhost:8000 also
This issue is resolved and I appreciate the quick response.
