### ISSUE TITLE
Error page message "Request failed" instead of inline error from laravel

### ISSUE THREAD

**Issue by Jimmylet** [cretueusebiu/laravel-nuxt#67]
Hello,

I try to make this package functional, but I can not do it. I followed the instructions with `composer create-project --prefer-dist cretueusebiu/laravel-nuxt`.

I can connect, it works. I can also edit my information, great.

Sadly, for example on the profile page, when I try not to fill a data (for example, the name), I have an error screen.

![image](https://user-images.githubusercontent.com/17065517/62233466-ef3b9000-b3c8-11e9-8910-8e0905a95546.png)

In the reply json, I get the errors of Laravel well.

My question: why this screen appears instead of errors below the input? What did I do wrong?

And also, I can't run the `npm run build`, error : `Error: ENOENT: no such file or directory, stat '/Users/.../miat/miath-app/dist/_nuxt'`

It may be related, I do not know

I use Homestead.

Thank you for your help

**Comment by cretueusebiu** [comment]
Because of some changes the in recent versions of Nuxt, it now shows that error in the page instead bellow the input, but that's just when you are in dev mode. Still annoying as hell. 

You have now to wrap all request in a try/catch block.

Not sure about the last error though... Will investigate.

**Comment by Jimmylet** [comment]
Hi @cretueusebiu 

Thanks for the information. Indeed, it works with the catch.

By cons, I still have the problem with the `npm run build`.

Thank you !

**Comment by adavie1** [comment]
> Hi @cretueusebiu
> 
> Thanks for the information. Indeed, it works with the catch.
> 
> By cons, I still have the problem with the `npm run build`.
> 
> Thank you !

Which requests need to be in a `try catch` block? Any code samples please?

**Comment by cretueusebiu** [comment]
Any axios or form requests should be wrapped in a try/catch block.

```javascript
try {
  this.form.post('/login')
} catch (e) {
}
```
