### ISSUE TITLE
Error on first install

### ISSUE THREAD

**Issue by adavie1** [cretueusebiu/laravel-nuxt#68]
Firstly, very happy to have this package available.

However, I'm having an issue when I start the app, first time.
Already done the `.env mods, npm install` etc.

This is what I see when running `php artisan serve --port 3000`:

![Selection_463](https://user-images.githubusercontent.com/3030402/62296606-04382200-b4a2-11e9-9279-239a7560d98c.png)

**Having read docs properly :-D**
I've now tried: `npm run dev` still get errors.
Even` npm run build` I also get this error:
![Selection_464](https://user-images.githubusercontent.com/3030402/62297225-6a717480-b4a3-11e9-814c-569072a99d80.png)

I've checked public dir, and yes, there's no `_nuxt\index.html` file. Have I missed a step somewhere?

**Comment by Jimmylet** [comment]
I have the same mistake #67

**Comment by adavie1** [comment]
@Jimmylet yes, I saw your issue- it seemed different than mine. Let's see from the developer if mine is a duplicate of yours.

**Comment by Jimmylet** [comment]
@adavie1, Your problem is not a duplicate. I did not open a specific issue for your problem, I briefly talked about it.

But I have exactly the same mistakes.

**Comment by adavie1** [comment]
The team at Nuxt suggested this:

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Which worked for me.

More details [here](https://github.com/nuxt/nuxt.js/issues/6172)
