### ISSUE TITLE
How to make this work in VPS and apache2?

### ISSUE THREAD

**Issue by jericopulvera** [cretueusebiu/laravel-nuxt#7]
I uploaded this on a VPS server.

after configuring .env I did 
npm run build 
npm run start

it outputs on console http://localhost:3000

but when I access it using my VPS IP like http://xxx.xx.xx.xxxx:3000 
it does not work.

**Comment by cretueusebiu** [comment]
You'll need to configure a proxy see https://github.com/cretueusebiu/laravel-nuxt#production-with-ssr
