### ISSUE TITLE
Feature Request: CSS framework agnostic or at least selectable.

### ISSUE THREAD

**Issue by adavie1** [cretueusebiu/laravel-nuxt#70]
Thanks for creating a great platform. However, Bootstrap is not my preferred CSS framework. Nuxt allows you to choose between a range of UI frameworks. Could that be added to the roadmap?

I'm happy to contribute as well, if you can give me some pointers as to where to change things.

**Comment by cretueusebiu** [comment]
Yes Nuxt allows you to choose a CSS framework, but for this template would mean that each page/component would have to be written and maintain for each framework.
