### ISSUE TITLE
Reasons for having an integrated laravel + nuxt monolith?

### ISSUE THREAD

**Issue by connecteev** [cretueusebiu/laravel-nuxt#71]
@cretueusebiu Thanks for this amazing repo. Though, one question I have is what are the advantages of having a monolith for Laravel (back-end) + Nuxt (front-end "client" folder) in one repository, versus keeping them in separate folders? Are there any pros to doing this?

My understanding is that in both cases, we will need 2 processes running to get this app working: one for ```php artisan serve``` and another for ```npm run dev``` (or it's equivalent on production). 
Besides the simplicity of having everything in one repository and folder....

1. Are there any advantages of not keeping the codebases separate for the front-end "client" folder and the rest of laravel? 
2. Is there any code sharing happening (like env variables)? 
3. Any other advantages to this approach that I am missing?

**Comment by cretueusebiu** [comment]
I usually split mine into client and api because the codebase it's pretty big.

Also if you would deploy the client to a different environment like an S3 bucket or a Lambda function you'd want them in separate repos.

**Comment by connecteev** [comment]
@cretueusebiu makes sense. Why not split this repo also, then, and take the client folder out? That's my question :)

**Comment by cretueusebiu** [comment]
It becomes too cumbersome to manage and release 2 repos for the same thing.

**Comment by connecteev** [comment]
Ah! Gotcha...so purely for convenience.
