### ISSUE TITLE
Admin route for backend

### ISSUE THREAD

**Issue by dilovar-91** [cretueusebiu/laravel-nuxt#73]
Good day Cretu. How can i allow admin route for building backend with laravel? And also why adding nuxt route is manually? Thank you for updating  laravel-nuxt.

**Comment by connecteev** [comment]
@dilovar-91 You can't combine nuxt with laravel and serve some routes from laravel and some from nuxt. They live on different ports. This is unfortunate but thats what I learned the hard way. I'd love for you (or someone) to prove me wrong though.

**Comment by jehadja** [comment]
simply : 
https://api.site.com --- serve your Laravel backend 
https://site.com  --- server you node server 
it works with me 100% just you need some updates on Auth logic to make it accept both types of login JWT +  session

**Comment by vahidalvandi** [comment]
Why we need nuxt except seo ! ? I need to have two server ... and two part of application
