### ISSUE TITLE
no such file or directory dist/_nuxt

### ISSUE THREAD

**Issue by Jimmylet** [cretueusebiu/laravel-nuxt#76]
Hello,

Whenever I try to launch a build of my application, I have this error at the end.

After invistigation, I think the problem comes from nuxt.config.js :

```
hooks: {
    build: {
      done (builder) {
        // Copy dist files to public/_nuxt
        if (builder.nuxt.options.dev === false && builder.nuxt.options.mode === 'spa') {
          const publicDir = join(builder.nuxt.options.rootDir, 'public', '_nuxt')
          removeSync(publicDir)
          copySync(join(builder.nuxt.options.generate.dir, '_nuxt'), publicDir)
          copySync(join(builder.nuxt.options.generate.dir, '200.html'), join(publicDir, 'index.html'))
        }
      }
    }
  }
```

As soon as I remove this code, the `npm run build` works. But of course, it does not generate the expected files so the application does not work.

Any idea ?

EDIT: If I copy/paste the files in `/public`, it works. But it's pretty boring.

I tested on two different Macs computers, a homestead and a Linux server. I have the same problem.

**Comment by jnickzlim** [comment]
I encounter the same issue  when running `npm run build` as well, tried create `dist/_nuxt` folder does not work as well, it generate another error:

> Error: ENOENT: no such file or directory, stat '/Applications/MAMP/htdocs/vue-app/dist/200.html'

Any idea on how to resolve this before i start using to develop application?

**Comment by Mesolo** [comment]
I am having the exact same issue.
Running on windows 10 with npm

**Comment by hiddehs** [comment]
The root cause of this error is that there are no pages generated yet by the time of finishing building (build done hook). In fact the [generator:done hook](https://nuxtjs.org/api/internals-generator#hooks) is also triggered when running ```yarn build``` for example. 

Simply change the following build hook code from your [```nuxt.config.js```](https://github.com/cretueusebiu/laravel-nuxt/blob/master/client/nuxt.config.js#L59)
```
    build: {
      done (builder) {
        // Copy dist files to public/_nuxt
        if (builder.nuxt.options.dev === false && builder.nuxt.options.mode === 'spa') {
          const publicDir = join(builder.nuxt.options.rootDir, 'public', '_nuxt')
          removeSync(publicDir)
          copySync(join(builder.nuxt.options.generate.dir, '_nuxt'), publicDir)
          copySync(join(builder.nuxt.options.generate.dir, '200.html'), join(publicDir, 'index.html'))
        }
      }
    }
```
into
```
    generate:{
      done(generator){
        // Copy dist files to public/_nuxt
        if (generator.nuxt.options.dev === false && generator.nuxt.options.mode === 'spa') {
          const publicDir = join(generator.nuxt.options.rootDir, 'public', '_nuxt')
            removeSync(publicDir)
            copySync(join(generator.nuxt.options.generate.dir, '_nuxt'), publicDir)
            copySync(join(generator.nuxt.options.generate.dir, '200.html'), join(publicDir, 'index.html'))
        }
      }
    }
```
- @cretueusebiu maybe a quick fix for people who wanna just use CSR?

This change ensures that copying the dist files (for Laravel routing) will take place **after** the build files exists in ```dist/_nuxt```

**Comment by soeurngsar** [comment]
Hello all dear,

I face the same problem like you all when I access http://127.0.0.1:8000 , but if you access on http://localhost:3000 after run dev it working fine.

**Comment by sergiooak** [comment]
I will add some prints to @hiddehs response before submitting a PR...
---
```js
    build: {
      done (builder) {
        // Copy dist files to public/_nuxt
        if (builder.nuxt.options.dev === false && builder.nuxt.options.mode === 'spa') {
          const publicDir = join(builder.nuxt.options.rootDir, 'public', '_nuxt')
          removeSync(publicDir)
          copySync(join(builder.nuxt.options.generate.dir, '_nuxt'), publicDir)
          copySync(join(builder.nuxt.options.generate.dir, '200.html'), join(publicDir, 'index.html'))
        }
        console.log("Before generate dist folder"); //
      }
    }
```
This will try to copy the content of the "dist" folder generate in Laravel root and move to "public" folder, but it fails case dist folder doesn't exist yet and throw this error:
![Error: ENOENT: no such file or directory, stat 'C:\laragon\www\mhb\dist\_nuxt'](https://user-images.githubusercontent.com/46563926/68064012-d35fc700-fcf4-11e9-96eb-5dba3047b878.png)

For test purpose, I've commented out this entire block, runs `npm build` so it creates the "dist" on Laravel root, then I uncommented the block and run  `npm build` again:
![image](https://user-images.githubusercontent.com/46563926/68064122-6b11e500-fcf6-11e9-9ace-80dce22553f9.png)
It worked, but you can see it runs before generate the dist folder.

---
So changing to this code block:
```js
generate:{
      done(generator){
        // Copy dist files to public/_nuxt
        if (generator.nuxt.options.dev === false && generator.nuxt.options.mode === 'spa') {
          const publicDir = join(generator.nuxt.options.rootDir, 'public', '_nuxt')
            removeSync(publicDir) //Clear content from previous builds
            copySync(join(generator.nuxt.options.generate.dir, '_nuxt'), publicDir)
            copySync(join(generator.nuxt.options.generate.dir, '200.html'), join(publicDir, 'index.html'))
            removeSync(generator.nuxt.options.generate.dir) //Delete 'Dist' folder from Laravel root
        }
        console.log("After generate dist folder");        
      }
    }
```
![image](https://user-images.githubusercontent.com/46563926/68063954-3866ed00-fcf4-11e9-8679-229853503ecc.png)
It just works! I've added `removeSync(generator.nuxt.options.generate.dir)` to delete original 'dist'

---
I'm making a PR right now...
