### ISSUE TITLE
show language code in url

### ISSUE THREAD

**Issue by vahidalvandi** [cretueusebiu/laravel-nuxt#78]
hi
how i can add language code in route 

ex: 
EN
https://laravel-nuxt.cretueusebiu.com/en/login

ES
https://laravel-nuxt.cretueusebiu.com/es/login

this very important in seo

**Comment by mariuszmalek** [comment]
In this link you have full instruction on how to do that:
https://medium.com/hypefactors/add-i18n-and-manage-translations-of-a-vue-js-powered-website-73b4511ca69c
