### ISSUE TITLE
public/.htaccess is not working on ssr mode.

### ISSUE THREAD

**Issue by jericopulvera** [cretueusebiu/laravel-nuxt#8]
public/.htaccess is not working on ssr mode.

where do I add htaccess when using ssr?

**Comment by cretueusebiu** [comment]
How is that not working ? Can you explain a bit ?

**Comment by jericopulvera** [comment]
I added some simple rewrite on to redirect https to http but it's not working. 

RewriteEngine On
RewriteCond %{HTTPS} on
RewriteRule (.*) http://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

and also did some syntax error .htaccess based on this tutorial
https://docs.bolt.cm/3.4/howto/making-sure-htaccess-works

but accessing the site still works.

**Comment by jericopulvera** [comment]
do I have to re run npm start build in order for the changes to reflect?

**Comment by cretueusebiu** [comment]
I think you're confusing the server and client.

When you run the application with `npm run start` the requests are handled directly by Nuxt's Node server.
Only the api calls to the server app are handled by Laravel.

So your htaccess won't work for the client.

If you read the readme you have an example on how to set up a Nginx Proxy where you probably could implement a redirect.

**Comment by jericopulvera** [comment]
I understand now. thanks!
