### ISSUE TITLE
Reset password fails if mail settings not specified

### ISSUE THREAD

**Issue by connecteev** [cretueusebiu/laravel-nuxt#82]
Note: everything works fine if you have valid mail settings in your .env file. However there are 2 use-cases when the user experience is poor.

1. If you delete all mail settings from .env, so there's no values for MAIL_DRIVER, MAIL_HOST, MAIL_PORT, MAIL_USERNAME, MAIL_PASSWORD, MAIL_ENCRYPTION

Then if you go to the reset password link:
http://localhost:8001/api/password/email
enter an email and press the 'reset password' button, you see a green SUCCESS message "We have e-mailed your password reset link!", even though the email was never sent.
Expected: Show a red error message, "Sorry, something went wrong. We could could not e-mail your password reset link".

Case 2
2. If the .env file does not contain valid mail settings, example:
```

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

```

then if you go to the reset password link:
http://localhost:8001/api/password/email
enter an email and press the 'reset password' button, the page dies with an error:

```
Cannot read property 'constructor' of undefined
An error occurred while rendering the page. Check developer tools console for details.
```
THis is what is shown in the console:
```
VM267:1 POST http://localhost:8001/api/password/email 500 (Internal Server Error)
(anonymous) @ VM267:1
dispatchXhrRequest @ commons.app.js:388
xhrAdapter @ commons.app.js:227
dispatchRequest @ commons.app.js:835
Promise.then (async)
request @ commons.app.js:637
wrap @ commons.app.js:1180
(anonymous) @ vendors.app.js:35390
submit @ vendors.app.js:35389
post @ vendors.app.js:35326
_callee$ @ 3.js:163
tryCatch @ commons.app.js:6292
invoke @ commons.app.js:6518
prototype.<computed> @ commons.app.js:6344
asyncGeneratorStep @ commons.app.js:31
_next @ commons.app.js:53
(anonymous) @ commons.app.js:60
(anonymous) @ commons.app.js:49
send @ 3.js:180
submit @ 3.js:217
invokeWithErrorHandling @ commons.app.js:13258
invoker @ commons.app.js:13583
original._wrapper @ commons.app.js:18306
vendors.app.js:17293 error TypeError: Cannot read property 'constructor' of undefined
    at SweetAlert (vendors.app.js:34749)
    at app.js:4513
```
The page should load and act gracefully.
Expected: Show a red error message, "Sorry, something went wrong. We could could not e-mail your password reset link".

**Comment by cretueusebiu** [comment]
Sometimes I forget myself to configure the mail and wonder why it doesn't work.
But I think this is more of a configuration check. Not sure it's specific to this template.
