### ISSUE TITLE
nuxt: not found

### ISSUE THREAD

**Issue by DengSihan** [cretueusebiu/laravel-nuxt#87]
I follow the README.md step by step to install the project.
When I try to run `npm run dev`, I got an error.

```
> @ start /home/vagrant/code/lanu
> nuxt start -c client/nuxt.config.js

sh: 1: nuxt: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ start: `nuxt start -c client/nuxt.config.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2019-12-12T15_17_36_020Z-debug.log
```
homestead 9.2.0
npm 6.13.1

I am sure I install the npm and nuxt correctly.
I googled it but nothing helps.

sorry for troubling and poor English, thanks a lot

**Comment by rajakhoury** [comment]
can you post your `package.json`? try changing `nuxt` to `node_modules/.bin/nuxt` in your scripts. e.g

    "scripts": {
        "dev": "node_modules/.bin/nuxt -c client/nuxt.config.js",
        "build": "node_modules/.bin/nuxt build -c client/nuxt.config.js",
        "start": "node_modules/.bin/nuxt start -c client/nuxt.config.js",
        "lint": "eslint --fix --ext .js,.vue client/"
      }

also see these [answers ](https://stackoverflow.com/questions/55997850/error-in-running-nuxt-project-nuxt-is-not-recognized-as-an-internal-or-exter)they may help you

**Comment by DengSihan** [comment]
> can you post your `package.json`? try changing `nuxt` to `node_modules/.bin/nuxt` in your scripts. e.g
> 
> ```
> "scripts": {
>     "dev": "node_modules/.bin/nuxt -c client/nuxt.config.js",
>     "build": "node_modules/.bin/nuxt build -c client/nuxt.config.js",
>     "start": "node_modules/.bin/nuxt start -c client/nuxt.config.js",
>     "lint": "eslint --fix --ext .js,.vue client/"
>   }
> ```
> 
> also see these [answers ](https://stackoverflow.com/questions/55997850/error-in-running-nuxt-project-nuxt-is-not-recognized-as-an-internal-or-exter)they may help you

@rajakhoury Thanks a lot !
I change the code in `package.json` from
```json
"scripts": {
    "dev": "nuxt -c client/nuxt.config.js",
    "build": "nuxt build -c client/nuxt.config.js",
    "start": "nuxt start -c client/nuxt.config.js",
    "lint": "eslint --fix --ext .js,.vue client/"
 }
```
to
```json
"scripts": {
    "dev": "node_modules/nuxt/bin/nuxt.js -c client/nuxt.config.js",
    "build": "node_modules/nuxt/bin/nuxt.js build -c client/nuxt.config.js",
    "start": "node_modules/nuxt/bin/nuxt.js start -c client/nuxt.config.js",
    "lint": "eslint --fix --ext .js,.vue client/"
 }
```
then it works.
