### ISSUE TITLE
Login with github in production

### ISSUE THREAD

**Issue by jericopulvera** [cretueusebiu/laravel-nuxt#9]
api.jerico.xyz/oauth/github/callback?code=8f153b514f42bd6d5c11:6 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:3000') does not match the recipient window's origin ('http://jerico.xyz').

**Comment by cretueusebiu** [comment]
Make sure to update `CLIENT_URL` in the .`env` to the actual url of the client app (http://jerico.xyz).
