### ISSUE TITLE
Can't deploy on cpanel.

### ISSUE THREAD

**Issue by tusharmangle** [cretueusebiu/laravel-nuxt#94]
How can we deploy this app to cpanel hosted apache server ?

**Comment by vahidalvandi** [comment]
nuxt need node server and you need install node server in your vps . if you use shared hosting maybe not working ...

**Comment by tusharmangle** [comment]
My nuxt is working properly but main problem is its not connecting to database in laravel application.

**Comment by vahidalvandi** [comment]
maybe you need DB_HOST=localhost Or you need upgrade php version to 7.2
