### ISSUE TITLE
why haver error 422 in register validator?

### ISSUE THREAD

**Issue by vahidalvandi** [cretueusebiu/laravel-nuxt#95]
![Screenshot from 2020-01-17 10-39-48](https://user-images.githubusercontent.com/7871623/72591605-cfb40780-3915-11ea-9a51-929aa56bdd08.png)

**Comment by vahidalvandi** [comment]
also in http://localhost:3000/settings/profile

**Comment by vahidalvandi** [comment]
![Screenshot from 2020-01-17 10-50-37](https://user-images.githubusercontent.com/7871623/72592172-400f5880-3917-11ea-8b57-d618691021bd.png)

**Comment by alidavid0418** [comment]
Hi
Maybe you run Nuxt as npm run build -> npm run start
and run laravel as php artisan serve
Please run laravel by php artisan serve --port=80
Then you can see it works well

**Comment by vahidalvandi** [comment]
i have installed apache in ubunto and can't run in port 80 . how i can use
`php artisan serve`
